language: node_js
node_js:
  - "12.19.0"
# command to install dependencies
sudo: true

addons:
  chrome: stable

branches:
  only:
    - master

before_script:
  - cd angular
  - npm install
  - ng update
  - npm update 

script:
  - ng test --watch=false --browsers=ChromeHeadless

