# Generated by Django 3.0.3 on 2020-03-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.IntegerField(default=1)),
                ('entry_time', models.DateTimeField()),
                ('process_start_time', models.DateTimeField()),
                ('process_end_time', models.DateTimeField()),
                ('routine', models.CharField(max_length=100)),
                ('item_id', models.CharField(max_length=70)),
                ('request_text', models.CharField(default='', max_length=1000)),
                ('nationality', models.CharField(default='FRA', max_length=3)),
                ('name', models.CharField(default='', max_length=70)),
                ('gender', models.CharField(default='m', max_length=1)),
            ],
        ),
    ]
