# Generated by Django 3.0.6 on 2020-09-08 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UCIrankingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField()),
                ('process_start_time', models.DateTimeField(blank=True, null=True)),
                ('process_end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=70)),
                ('routine', models.CharField(max_length=100)),
                ('item_id', models.CharField(max_length=70)),
                ('log', models.TextField(blank=True)),
                ('result_file_name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField()),
                ('process_start_time', models.DateTimeField(blank=True, null=True)),
                ('process_end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=70)),
                ('routine', models.CharField(max_length=100)),
                ('item_id', models.CharField(max_length=70)),
                ('log', models.TextField(blank=True)),
                ('name', models.CharField(default='team', max_length=100)),
                ('year', models.IntegerField()),
                ('nationality', models.CharField(blank=True, max_length=3)),
                ('UCIcode', models.CharField(blank=True, max_length=3)),
                ('result_id', models.CharField(blank=True, max_length=30)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StartListRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField()),
                ('process_start_time', models.DateTimeField(blank=True, null=True)),
                ('process_end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=70)),
                ('routine', models.CharField(max_length=100)),
                ('item_id', models.CharField(max_length=70)),
                ('log', models.TextField(blank=True)),
                ('result_file_name', models.CharField(max_length=100)),
                ('time_of_race', models.DateTimeField()),
                ('race_type', models.BooleanField()),
                ('chrono', models.BooleanField()),
                ('moment', models.BooleanField()),
                ('gender', models.CharField(blank=True, max_length=5)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StagesRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField()),
                ('process_start_time', models.DateTimeField(blank=True, null=True)),
                ('process_end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=70)),
                ('routine', models.CharField(max_length=100)),
                ('item_id', models.CharField(max_length=70)),
                ('log', models.TextField(blank=True)),
                ('prologue', models.BooleanField()),
                ('last_stage', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SortNameRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField()),
                ('process_start_time', models.DateTimeField(blank=True, null=True)),
                ('process_end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=70)),
                ('routine', models.CharField(max_length=100)),
                ('item_id', models.CharField(max_length=70)),
                ('log', models.TextField(blank=True)),
                ('prop', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SortDateRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField()),
                ('process_start_time', models.DateTimeField(blank=True, null=True)),
                ('process_end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=70)),
                ('routine', models.CharField(max_length=100)),
                ('item_id', models.CharField(max_length=70)),
                ('log', models.TextField(blank=True)),
                ('prop', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RaceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField()),
                ('process_start_time', models.DateTimeField(blank=True, null=True)),
                ('process_end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=70)),
                ('routine', models.CharField(max_length=100)),
                ('item_id', models.CharField(max_length=70)),
                ('log', models.TextField(blank=True)),
                ('name', models.CharField(default='race', max_length=100)),
                ('time_of_race', models.DateTimeField()),
                ('end_of_race', models.DateTimeField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=3)),
                ('result_id', models.CharField(blank=True, max_length=30)),
                ('race_type', models.BooleanField()),
                ('race_class', models.CharField(blank=True, max_length=20)),
                ('create_stages', models.BooleanField(blank=True)),
                ('prologue', models.BooleanField(blank=True)),
                ('last_stage', models.IntegerField(blank=True)),
                ('edition_nr', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NationalOneChampRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField()),
                ('process_start_time', models.DateTimeField(blank=True, null=True)),
                ('process_end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=70)),
                ('routine', models.CharField(max_length=100)),
                ('item_id', models.CharField(max_length=70)),
                ('log', models.TextField(blank=True)),
                ('nationality', models.CharField(blank=True, max_length=3)),
                ('year_begin', models.IntegerField()),
                ('year_end', models.IntegerField()),
                ('category', models.CharField(blank=True, max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NationalAllChampsRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField()),
                ('process_start_time', models.DateTimeField(blank=True, null=True)),
                ('process_end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=70)),
                ('routine', models.CharField(max_length=100)),
                ('item_id', models.CharField(max_length=70)),
                ('log', models.TextField(blank=True)),
                ('year', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportClassificationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField()),
                ('process_start_time', models.DateTimeField(blank=True, null=True)),
                ('process_end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=70)),
                ('routine', models.CharField(max_length=100)),
                ('item_id', models.CharField(max_length=70)),
                ('log', models.TextField(blank=True)),
                ('result_file_name', models.CharField(max_length=100)),
                ('classification_type', models.IntegerField()),
                ('year', models.IntegerField(default=2020)),
                ('gender', models.CharField(blank=True, max_length=5)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreateRiderRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField()),
                ('process_start_time', models.DateTimeField(blank=True, null=True)),
                ('process_end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=70)),
                ('routine', models.CharField(max_length=100)),
                ('item_id', models.CharField(max_length=70)),
                ('log', models.TextField(blank=True)),
                ('nationality', models.CharField(blank=True, max_length=3)),
                ('name', models.CharField(blank=True, max_length=70)),
                ('gender', models.CharField(blank=True, max_length=5)),
                ('result_id', models.CharField(blank=True, max_length=30)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
