# Generated by Django 3.0.3 on 2020-03-31 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=70)),
                ('firstName', models.CharField(max_length=70)),
                ('lastName', models.CharField(max_length=70)),
                ('token', models.CharField(max_length=70)),
                ('level', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='botrequest',
            name='status',
            field=models.CharField(default='pending', max_length=70),
        ),
        migrations.AlterField(
            model_name='botrequest',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_requests.User'),
        ),
    ]
