# Generated by Django 3.0.6 on 2020-10-20 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot_requests', '0002_startlistrequest_force_nation_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalTeamRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField()),
                ('process_start_time', models.DateTimeField(blank=True, null=True)),
                ('process_end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=70)),
                ('routine', models.CharField(max_length=100)),
                ('item_id', models.CharField(max_length=70)),
                ('log', models.TextField(blank=True)),
                ('nationality', models.CharField(blank=True, max_length=3)),
                ('year_begin', models.IntegerField()),
                ('year_end', models.IntegerField()),
                ('gender', models.CharField(max_length=5)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
