# Generated by Django 3.0.3 on 2020-04-19 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot_requests', '0003_auto_20200331_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateRiderRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField()),
                ('process_start_time', models.DateTimeField(blank=True)),
                ('process_end_time', models.DateTimeField(blank=True)),
                ('status', models.CharField(default='pending', max_length=70)),
                ('routine', models.CharField(max_length=100)),
                ('item_id', models.CharField(max_length=70)),
                ('nationality', models.CharField(blank=True, max_length=3)),
                ('name', models.CharField(blank=True, max_length=70)),
                ('gender', models.CharField(blank=True, max_length=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='BotRequest',
        ),
    ]
