# Generated by Django 3.0.6 on 2020-11-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_requests', '0003_nationalteamrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='racerequest',
            name='gender',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='stagesrequest',
            name='gender',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
