# Generated by Django 3.0.3 on 2020-04-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_requests', '0004_auto_20200419_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createriderrequest',
            name='process_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='createriderrequest',
            name='process_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
