# Generated by Django 3.0.6 on 2020-11-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_requests', '0004_auto_20201101_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucirankingrequest',
            name='gender',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
