# Generated by Django 3.0.3 on 2020-04-27 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_requests', '0006_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
