# Generated by Django 3.0.6 on 2020-12-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_requests', '0006_ucirankingrequest_uciranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucirankingrequest',
            name='bypass',
            field=models.BooleanField(default=False),
        ),
    ]
