# Generated by Django 3.1.7 on 2021-03-07 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_requests', '0009_auto_20210207_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nationalteamrequest',
            name='gender',
        ),
    ]
