# Generated by Django 3.0.6 on 2020-06-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_requests', '0009_auto_20200622_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='racerequest',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
