# Generated by Django 3.2.8 on 2022-01-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_requests', '0010_remove_nationalteamrequest_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamrequest',
            name='category_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
