# Generated by Django 3.0.6 on 2020-06-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_requests', '0010_racerequest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racerequest',
            name='end_of_race',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='racerequest',
            name='last_stage',
            field=models.IntegerField(blank=True),
        ),
    ]
