# Generated by Django 3.0.6 on 2020-06-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_requests', '0011_auto_20200629_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racerequest',
            name='create_stages',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='racerequest',
            name='prologue',
            field=models.BooleanField(blank=True),
        ),
    ]
