# Generated by Django 3.0.6 on 2020-06-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_requests', '0012_auto_20200630_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamrequest',
            name='name',
            field=models.CharField(default='team', max_length=20),
        ),
        migrations.AlterField(
            model_name='racerequest',
            name='name',
            field=models.CharField(default='race', max_length=20),
        ),
    ]
