# Generated by Django 3.0.6 on 2020-07-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_requests', '0013_auto_20200630_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationalonechamprequest',
            name='category',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='createriderrequest',
            name='gender',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
