# Generated by Django 3.0.6 on 2020-08-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_requests', '0014_auto_20200708_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='createriderrequest',
            name='log',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='createriderrequest',
            name='result_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='importclassificationrequest',
            name='log',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nationalallchampsrequest',
            name='log',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nationalonechamprequest',
            name='log',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='racerequest',
            name='log',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='racerequest',
            name='result_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='sortdaterequest',
            name='log',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sortnamerequest',
            name='log',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stagesrequest',
            name='log',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='startlistrequest',
            name='gender',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='startlistrequest',
            name='log',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teamrequest',
            name='log',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teamrequest',
            name='result_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='ucirankingrequest',
            name='log',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='racerequest',
            name='name',
            field=models.CharField(default='race', max_length=100),
        ),
        migrations.AlterField(
            model_name='teamrequest',
            name='name',
            field=models.CharField(default='team', max_length=100),
        ),
    ]
