# Generated by Django 3.0.6 on 2020-08-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_requests', '0015_auto_20200822_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='importclassificationrequest',
            name='year',
            field=models.IntegerField(default=2020),
        ),
    ]
