# Generated by Django 3.0.6 on 2020-08-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_requests', '0016_importclassificationrequest_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='importclassificationrequest',
            name='gender',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
