apiVersion: apps/v1
kind: Deployment
metadata:
  name: cycling-init-bot.worker
  namespace: tool-cycling-init-bot
  labels:
    name: cycling-init-bot.worker
    toolforge: tool
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cycling-init-bot.worker
      toolforge: tool
  template:
    metadata:
      labels:
        name: cycling-init-bot.worker
        toolforge: tool
    spec:
      containers:
        - name: celery
          image: docker-registry.tools.wmflabs.org/toolforge-python35-sssd-web:latest
          command: [ "/data/project/cycling-init-bot/www/python/src/script/celery.sh" ]
          workingDir: /data/project/cycling-init-bot/www/python/src
          env:
            - name: HOME
              value: /data/project/cycling-init-bot
          imagePullPolicy: Always
          volumeMounts:
            - name: home
              mountPath: /data/project/cycling-init-bot/
      volumes:
        - name: home
          hostPath:
            path: /data/project/cycling-init-bot/
